#!/bin/bash
shopt -s nullglob
shopt -s nocasematch

read -p "please enter your ip:" ipinput
ssh -o strictHostKeyChecking=no $ipnput -l root <<HERE
main
HERE

vminstall() {
wget http://10.1.8.47/VmwareTools10.0.9.tar.gz -P /tmp/vm-tools
tar -zxvf /tmp/vmware-tools/VmwareTools10.0.9.tar.gz -C /tmp/vm-tools
cd /tmp/vm-tools/vmware-tools-distrib/
./vmware-install.pl -d
rm -Rf /tmp/vm-tools
}

main() {

if grep -q 'centos\|ubuntu\|redhat' /etc/*release 1>/dev/null; then
 if service vmware-tools status | grep run 1>/dev/null; then
 vmware-uninstall-tools.pl &&
 vminstall
 else
 vminsatll
 fi
else
echo "it not a linux machhine"
exit 1
fi
}
